version: '3'

services:
  django:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    image: hillel_django
    container_name: hillel_django
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes: 
      - ./src:/app/src
  postgres:
    image: postgres:13.3
    env_file: ".env"
    ports:
      - "5432:5432"
    volumes: 
    - pg_data:/var/lib//postgresql/data

volumes:
  pg_data: {}